#!/usr/bin/env python
"""E0.2 tranche 2 — judge vote aggregation, scoring + report
(pre-registered: experiments/e02_t2_voting_prereg.yaml).

Arm A (zero-token replay): recompute tranche-1 unknown-flaw and
known-flaw catch rates from the committed per-seat raw judgments
(experiments/e02_t1_items/judgments.jsonl) for the same-family and
cross-family pairs under BOTH vote rules:
  require-both   (incumbent): a flaw is caught iff BOTH seats flag it
  either-suffices           : a flaw is caught iff EITHER seat flags it

Arm B (live, run before this script): 40 flaw-free artifacts
(clean_items.json, hidden annotation clean=true) generated by the
tranche-1 adversary pipeline in clean mode and judged by the same four
seat configurations (experiments/e02_t2_items/judgments.jsonl).
False-positive rate per rule = fraction of clean items flagged.

Verdicts against the prereg's literal numbers (cross-family pair is the
adoption candidate; same-family reported alongside):
  P1 CONFIRMED iff either-suffices cross-family unknown-flaw catch rate
     >= 0.55; REFUTED otherwise.
  P2 CONFIRMED iff either-suffices clean FP rate (cross-family) <= 0.25;
     REFUTED iff > 0.40 (vote change rejected as too expensive
     regardless of catch gains); else UNDECIDED.
  P3 CONFIRMED iff the pp gain in unknown-flaw catch (either-suffices
     minus require-both, cross-family) exceeds the pp rise in clean-item
     false positives (same delta, cross-family); REFUTED otherwise.

Adoption note: per the prereg, vote-rule adoption additionally requires
the recusal design requirement, untestable on this fixture; P3 alone
does not adopt.

Usage: python scripts/e02_t2_score.py
         [--t1-items-dir experiments/e02_t1_items]
         [--t2-items-dir experiments/e02_t2_items]
         [--out-dir experiments/results]
"""

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

PREREG = "experiments/e02_t2_voting_prereg.yaml"
SCHEMA = "deepreason-e02-t2-report-v1"
PAIRS = {"same_family": ("same-A", "same-B"),
         "cross_family": ("cross-A", "cross-B")}
RULES = ("require_both", "either_suffices")
T2_TOKEN_CEILING = 400_000


def load_seats(path: Path) -> dict[tuple[str, str], dict]:
    seats: dict[tuple[str, str], dict] = {}
    for line in path.read_text().splitlines():
        rec = json.loads(line)
        seats[(rec["item_id"], rec["seat"])] = rec  # last write wins
    return seats


def pair_flags(seats, item_id: str, pair: str) -> dict:
    a, b = (seats[(item_id, s)] for s in PAIRS[pair])
    votes = [bool(a["flawed"]), bool(b["flawed"])]
    return {
        "votes": votes,
        "require_both": all(votes),
        "either_suffices": any(votes),
        "split": votes[0] != votes[1],
        "parse_failures": [bool(a.get("parse_failure")),
                           bool(b.get("parse_failure"))],
    }


def rate_row(rows: list[dict], pair: str, rule: str) -> dict:
    flagged = sum(r["pairs"][pair][rule] for r in rows)
    splits = sum(r["pairs"][pair]["split"] for r in rows)
    return {"n": len(rows), "flagged": flagged,
            "splits_1_1": splits,
            "rate": round(flagged / len(rows), 4) if rows else None}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--t1-items-dir", default="experiments/e02_t1_items")
    parser.add_argument("--t2-items-dir", default="experiments/e02_t2_items")
    parser.add_argument("--out-dir", default="experiments/results")
    args = parser.parse_args()
    t1 = REPO / args.t1_items_dir
    t2 = REPO / args.t2_items_dir
    out_dir = REPO / args.out_dir if not Path(args.out_dir).is_absolute() \
        else Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------ #
    # Load: t1 flawed batteries + t2 clean battery, seat verdicts each.
    # ------------------------------------------------------------------ #
    items: list[dict] = []
    for name in ("unknown_flaws.json", "known_flaws.json"):
        items.extend(json.loads((t1 / name).read_text()))
    clean_items = json.loads((t2 / "clean_items.json").read_text())
    assert len(clean_items) == 40, f"expected 40 clean items, {len(clean_items)}"
    assert all(item.get("clean") is True for item in clean_items)
    items.extend(clean_items)

    seats = load_seats(t1 / "judgments.jsonl")
    seats.update(load_seats(t2 / "judgments.jsonl"))

    per_item = []
    for item in sorted(items, key=lambda i: i["id"]):
        per_item.append({
            "id": item["id"],
            "sub_battery": item["sub_battery"],
            "class": item.get("flaw_class") or ("clean" if item.get("clean")
                                                else None),
            "pairs": {pair: pair_flags(seats, item["id"], pair)
                      for pair in PAIRS},
        })
    batteries = {
        "unknown_flaw": [r for r in per_item if r["sub_battery"] == "unknown_flaw"],
        "known_flaw": [r for r in per_item if r["sub_battery"] == "known_flaw"],
        "clean": [r for r in per_item if r["sub_battery"] == "clean"],
    }
    assert all(len(rows) == 40 for rows in batteries.values())

    # ------------------------------------------------------------------ #
    # Full rate table: rule x pair x battery. For flawed batteries the
    # rate is a CATCH rate; for the clean battery it is a FALSE-POSITIVE
    # rate (fraction of clean items flagged as flawed).
    # ------------------------------------------------------------------ #
    table = {rule: {pair: {battery: rate_row(rows, pair, rule)
                           for battery, rows in batteries.items()}
                    for pair in PAIRS}
             for rule in RULES}

    def rate(rule, pair, battery):
        return table[rule][pair][battery]["rate"]

    # ------------------------------------------------------------------ #
    # Verdicts (cross-family = adoption candidate).
    # ------------------------------------------------------------------ #
    p1_rate = rate("either_suffices", "cross_family", "unknown_flaw")
    p1 = "CONFIRMED" if p1_rate >= 0.55 else "REFUTED"

    fp_either_cross = rate("either_suffices", "cross_family", "clean")
    p2 = ("CONFIRMED" if fp_either_cross <= 0.25
          else "REFUTED" if fp_either_cross > 0.40 else "UNDECIDED")

    catch_gain_pp = round(
        (rate("either_suffices", "cross_family", "unknown_flaw")
         - rate("require_both", "cross_family", "unknown_flaw")) * 100, 2)
    fp_rise_pp = round(
        (rate("either_suffices", "cross_family", "clean")
         - rate("require_both", "cross_family", "clean")) * 100, 2)
    p3 = "CONFIRMED" if catch_gain_pp > fp_rise_pp else "REFUTED"

    verdicts = {
        "P1": {"verdict": p1,
               "measured": {
                   "cross_family_either_suffices_unknown_catch": p1_rate,
                   "cross_family_require_both_unknown_catch":
                       rate("require_both", "cross_family", "unknown_flaw"),
                   "t1_baseline_require_both": 0.175},
               "threshold": ">= 0.55"},
        "P2": {"verdict": p2,
               "measured": {
                   "cross_family_either_suffices_clean_fp": fp_either_cross,
                   "same_family_either_suffices_clean_fp":
                       rate("either_suffices", "same_family", "clean")},
               "thresholds": {"confirm": "<= 0.25",
                              "reject_vote_change": "> 0.40"}},
        "P3": {"verdict": p3,
               "measured": {"unknown_catch_gain_pp_cross_family": catch_gain_pp,
                            "clean_fp_rise_pp_cross_family": fp_rise_pp,
                            "net_pp": round(catch_gain_pp - fp_rise_pp, 2)},
               "threshold": "catch gain pp > FP rise pp"},
    }

    adoption = {
        "adoption_condition": ("adoption requires BOTH a confirmed P3 AND "
                               "the recusal design requirement (untestable "
                               "on this fixture; registered as binding for "
                               "the live adoption experiment)"),
        "p3_confirmed": p3 == "CONFIRMED",
        "recusal_requirement_tested_here": False,
        "adopted_by_this_experiment": False,
    }

    # ------------------------------------------------------------------ #
    # Token spend: tranche-2 ledger (live spend under the 400k cap) plus
    # the tranche-1 ledger for context (arm A spent zero new tokens).
    # ------------------------------------------------------------------ #
    t2_usage = json.loads((t2 / "token_usage.json").read_text())
    t1_usage = json.loads((t1 / "token_usage.json").read_text())
    t2_total = t2_usage["prompt_tokens"] + t2_usage["completion_tokens"]
    assert t2_total <= T2_TOKEN_CEILING, f"t2 spend {t2_total} over cap"

    seat_calls = [rec for (item_id, _s), rec in seats.items()
                  if any(item_id == r["id"] for r in batteries["clean"])]
    clean_parse_failures = sum(bool(r.get("parse_failure")) for r in seat_calls)

    caveats = [
        "Arm A is a zero-token re-aggregation of the tranche-1 raw seat "
        "verdicts; per the prereg this file was committed before the first "
        "look at per-seat union behavior.",
        "Clean items are generated-as-sound by the tranche-1 adversary "
        "model (deepseek-v4-pro) under a soundness prompt and mechanical "
        "validation only; soundness was not independently verified, so any "
        "genuinely defective 'clean' item inflates the measured "
        "false-positive rate (conservative against either-suffices).",
        "Topic-pool mismatch: all 40 clean items draw from the restricted "
        "safe-topic pool, while part of the tranche-1 unknown-flaw corpus "
        "predates that restriction; catch and FP rates therefore come from "
        "overlapping but not identical topic distributions.",
        "P2/P3 verdicts are evaluated on the cross-family pair (the "
        "adoption candidate named by P1/P3); the same-family rates are "
        "reported in the same table.",
        f"Clean-arm seat parse failures: {clean_parse_failures} of "
        f"{len(seat_calls)} seat calls (parse failures count as "
        "flawed=false, i.e. against catching and against false-positives).",
        "1-1 pair splits are reported per battery; under require-both a "
        "split is a no-catch (and a no-flag on clean items), under "
        "either-suffices it is a catch (and a false positive on clean "
        "items).",
        "Vote-rule adoption is NOT effected by this report: the prereg "
        "conditions adoption on P3 AND the recusal design requirement, "
        "which this fixture cannot test.",
    ]

    report = {
        "schema": SCHEMA,
        "prereg": PREREG,
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "design": {
            "arm_a": "zero-token re-aggregation of tranche-1 judgments",
            "arm_b": "40 clean items generated (clean mode) + judged live",
            "judges": {"same_family_pair": ["gpt-oss:120b", "gpt-oss:120b"],
                       "cross_family_pair": ["gpt-oss:120b", "qwen3-coder:480b"],
                       "temperature": 0.0},
            "adversary_model_clean_mode": "deepseek-v4-pro",
            "concurrency_max_in_flight": 3,
        },
        "volumes": {battery: len(rows) for battery, rows in batteries.items()},
        "rate_table": {
            "structure": "rule -> pair -> battery; rate is catch rate for "
                         "unknown_flaw/known_flaw, false-positive rate for "
                         "clean",
            **table,
        },
        "verdicts": verdicts,
        "adoption": adoption,
        "token_spend": {
            "tranche2_live": t2_usage,
            "tranche2_total_tokens": t2_total,
            "tranche2_ceiling": T2_TOKEN_CEILING,
            "tranche1_ledger_context": {
                "total_tokens": (t1_usage["prompt_tokens"]
                                 + t1_usage["completion_tokens"]),
                "note": "arm A re-used these committed judgments at zero "
                        "new cost"},
        },
        "caveats": caveats,
        "per_item": per_item,
    }
    report_path = out_dir / "e02_t2_voting_report.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n")

    index_path = out_dir / f"INDEX_{dt.date.today().isoformat()}.md"
    index_line = (
        f"\n## E0.2 judge vote aggregation, tranche 2 "
        f"({dt.date.today().isoformat()})\n\n"
        f"P1 {p1} (cross-family either-suffices unknown catch {p1_rate}), "
        f"P2 {p2} (cross-family either-suffices clean FP {fp_either_cross}), "
        f"P3 {p3} (catch gain {catch_gain_pp:+.1f}pp vs FP rise "
        f"{fp_rise_pp:+.1f}pp). {t2_total} live LLM tokens (cap "
        f"{T2_TOKEN_CEILING}). Prereg: `{PREREG}`. Report: "
        f"`experiments/results/e02_t2_voting_report.json`. Adoption "
        f"withheld pending recusal requirement.\n")
    with index_path.open("a") as fh:
        fh.write(index_line)

    print(json.dumps({
        "verdicts": {k: v["verdict"] for k, v in verdicts.items()},
        "rate_table": {rule: {pair: {b: table[rule][pair][b]["rate"]
                                     for b in batteries}
                              for pair in PAIRS} for rule in RULES},
        "catch_gain_pp": catch_gain_pp, "fp_rise_pp": fp_rise_pp,
        "t2_tokens": t2_total,
    }, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
